### ISSUE TITLE
Trial limits

### ISSUE THREAD

**Issue by siruslan** [jelastic-jps/magento-cluster#1]
I tried to install it on Infortelecom w/o success due to the trial limits 
`Response:{"result":2338,"error":"maxnodescount count equals 8"}`
It should be mentioned that it works for paid users or at hosters with bigger limits.

**Comment by mommaroodles** [comment]
I noticed too that it's only setting up auto scaling for Memory not CPU as what it appears to have done previously on a full account - am just wondering if this is what's intended

**Comment by sych74** [comment]
Thanks for noticing this, auto-scaling should work based on CPU and this will be fixed with the next package update in the near time.

**Comment by sych74** [comment]
Trial limitatations depend on the specific hosting provider.
The common practice for trial accounts:
- public IPs are disabled
- number of containers is limited
